name: 'Liferay-74-mysql'
version: '0.1'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mnt/mysql/conf.d:/etc/mysql/conf.d
      - ./mnt/mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-data-mysql:/var/lib/mysql
    networks:
      - liferay-network

  elasticsearch:
    image: elasticsearch:7.17.8
    environment:
    #  - discovery.type=single-node
    #  - cluster.name=LiferayElasticsearchCluster
    #  - xpack.security.enabled=false
    #  - network.bind_host=_local_
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./mnt/elasticsearch/config\elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - liferay-network

  liferay:
    image: liferay/portal:7.4.3.56-ga56
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - JAVA_VERSION=zulu11
    #ports:
    #  - "8080:8080"
    #  - "11311:11311"
    expose: 
     - "8080"
    volumes:
      - ./mnt/liferay/files:/mnt/liferay/files
      - ./mnt/liferay/scripts:/mnt/liferay/scripts
      - ./mnt/liferay/deploy:/mnt/liferay/deploy
      - ./data/liferay/data:/opt/liferay/data
    networks:
      - liferay-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./mnt/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - liferay
    networks:
      - liferay-network

networks:
  liferay-network:
    driver: bridge

volumes:
  db-data-mysql: